unit TestLogUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Winapi.Windows, System.Variants,
  System.Classes, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages, Unit1;

type
  TestLog = class(TTestCase)
  strict private
     FLog1: Log;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRead(fileName: string);
  end;

implementation

procedure TestLog.SetUp;
begin
   FLog1:= Log.Create;
end;

procedure TestLog.TearDown;
begin
   FLog1.Free;
   FLog1 := nil;
end;

procedure TestLog.TestRead(fileName: string);
begin
  FLog1.read(fileName);
  CheckNotNull(FLog1.getTable);
end;

initialization

   // Register any test cases with the test runner
   RegisterTest(TestLog.Suite);

end.
