unit TestGeneralUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Winapi.Windows, System.Variants,
  System.Classes, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages;

type
  TestGeneral = class(TTestCase)
  const
    LogPath = '/var/log/apache/access.log';
    StartDate = '10/May/2019';
    EndDate = '12/May/2019';
  strict private
    FGeneral: General;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetLogPath;
  end;

implementation

procedure TestGeneral.SetUp;
begin
  FGeneral := General.Create(LogPath, StartDate, EndDate);
end;

procedure TestGeneral.TearDown;
begin
  FGeneral.Free;
  FGeneral := nil;
end;

procedure TestGeneral.TestGetLogPath;
begin
  CheckEqualsString(FGeneral.GetLogPath, LogPath);
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestGeneral.Suite);

end.
