unit TestGeneralUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  GeneralUnit {General} ,
  GeneralInterfaceUnit {GeneralInterface} ,
  TestFramework, System.SysUtils, Vcl.Graphics, Winapi.Windows, System.Variants,
  System.Classes, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages;

type
  TestGeneral = class(TTestCase)
  const
    LogPath = 'C:\_GIT\IRBIS\Test\Win32\Debug\access.log';
    StartDate = 43460; // 0 12/30/1899 12:00 am
    EndDate = 43462; // 2.75 1/1/1900 6:00 pm
  strict private
    FGeneral: General;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    // procedure TestGetLogPath;
    procedure TestRead;
  end;

implementation

procedure TestGeneral.SetUp;
begin
  FGeneral := General.Create(LogPath, StartDate, EndDate);
end;

procedure TestGeneral.TearDown;
begin
  FGeneral.Free;
  FGeneral := nil;
end;

procedure TestGeneral.TestRead;
var
i: integer;
begin
  FGeneral.Read;
  CheckNotNull(FGeneral);
end;

{
  procedure TestGeneral.TestGetLogPath;
  begin
  CheckEqualsString(FGeneral.GetLogPath, LogPath);
  end;
}
initialization

// Register any test cases with the test runner
RegisterTest(TestGeneral.Suite);

end.
